spring:
  application:
    name: sobee
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

finance:
  api:
    key: ${FINANCE_API_KEY}


cardgorilla:
  api:
    url: https://api.cardgorilla.com
    key: ${CARDGORILLA_API_KEY}   # 환경변수로 관리

fss:
  api:
    url: https://finlife.fss.or.kr/finlifeapi
    key: ${FINANCE_API_KEY}   # ← 이렇게 변경